### ISSUE TITLE
Terminating app due to uncaught exception 'ObjCRuntime.RuntimeException'

### ISSUE THREAD

**Issue by FA72** [BranchMetrics/xamarin-branch-deep-linking-attribution#165]
### Describe the bug

Hello!
I tried to start my app on iOS, but get this exception

2024-11-15 13:48:33.806 MyApp.IOS[3349:1619377] Received unhandled Objective-C exception that was marshalled from a managed exception: Could not find the type 'ObjCRuntime.__Registrar__' in the assembly 'BranchSDK.iOSBinding'. (ObjCRuntime.RuntimeException)
   at ObjCRuntime.RegistrarHelper.GetMapEntry(String assemblyName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/RegistrarHelper.cs:line 105
   at ObjCRuntime.RegistrarHelper.GetMapEntry(Assembly assembly) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/RegistrarHelper.cs:line 93
   at ObjCRuntime.RegistrarHelper.LookupRegisteredType(Assembly assembly, UInt32 id) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/RegistrarHelper.cs:line 199
   at ObjCRuntime.Class.ResolveToken(Assembly assembly, Module module, UInt32 token) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Class.cs:line 521
   at ObjCRuntime.Class.ResolveFullTokenReference(UInt32 token_reference) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Class.cs:line 449
   at ObjCRuntime.Class.ResolveTokenReference(UInt32 token_reference, UInt32 implicit_token_type) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Class.cs:line 486
   at ObjCRuntime.Class.ResolveTypeTokenReference(UInt32 token_reference) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Class.cs:line 454
   at ObjCRuntime.Class.FindType(NativeHandle class, Boolean& is_custom_type) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Class.cs:line 423
   at ObjCRuntime.Class.Lookup(IntPtr klass, Boolean throw_on_error) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Class.cs:line 222
   at ObjCRuntime.Class.Lookup(IntPtr klass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Class.cs:line 213
   at ObjCRuntime.Runtime.GetNSObject[Branch](IntPtr ptr, IntPtr sel, RuntimeMethodHandle method_handle, Boolean evenInFinalizerQueue) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 1882
   at ObjCRuntime.Runtime.GetNSObject[Branch](IntPtr ptr, IntPtr sel, RuntimeMethodHandle method_handle) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 1860
   at ObjCRuntime.Runtime.GetNSObject[Branch](IntPtr ptr) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 1855
   at IOSNativeBranch.Branch.GetInstance(String branchKey)
   at BranchSDK.BranchIOS.get_NativeBranch()
   at BranchSDK.BranchIOS.Init(String branchKey, NSDictionary launchOptions, IBranchBUOSessionInterface callback)
   at CardsIOS.AppDelegate.InitConfigurations(NSDictionary launchOptions) in /Users/pavelderevyankin/RiderProjects/MyApp.MobileApp/Cards.IOS/AppDelegate.cs:line 257
   at CardsIOS.AppDelegate.WillFinishLaunching(UIApplication application, NSDictionary launchOptions) in /Users/pavelderevyankin/RiderProjects/MyApp.MobileApp/Cards.IOS/AppDelegate.cs:line 97
   at CardsIOS.AppDelegate.__Registrar_Callbacks__.callback_9_CardsIOS_AppDelegate_WillFinishLaunching(IntPtr pobj, IntPtr sel, IntPtr p0, IntPtr p1, IntPtr* exception_gchandle)

### Steps to reproduce

1. Build Project with branch-xamarin-linking-sdk/9.0.1
2. Start on real device
3. Get Error

### Expected behavior

Just worked app =)

### SDK Version

9.0.0

### Make and Model

iPhone 11 Pro

### OS

iOS 17.4.1

**Comment by robin-schroeder-merc** [comment]
What is the status on this bug? We are experiencing the same.

**Comment by FA72** [comment]
@robin-schroeder-merc @mattpearcefanhub 
I have workaround https://blog.ostebaronen.dk/2024/11/dotnet9-gotchas.html
It's problem with .Net9. I think, no problem with branch. May be it's help you.

**Comment by mattpearcefanhub** [comment]
That sorted it for me, thanks @FA72 !
